### ISSUE TITLE
Hope to get the battery power of the connected Bluetooth device

### ISSUE THREAD

**Issue by anyiblog** [toy/blueutil#61] opened 2021-11-17 08:44 UTC
The system I use is monterey, and the official has been able to get the battery power of third-party Bluetooth devices. I hope the author can update the script, thank you

**Comment by toy** [comment] 2021-11-17 22:02
@anyiblog Thank you for opening the issue, but I think it is a duplicate of #35

**Comment by toy** [comment] 2021-12-09 20:20
Closing as duplicate of #35, please reopen if you think it is not

**Closed by toy** 2021-12-09 20:20 UTC
